"""Local build artifacts for Conflate programs.

The build format is intentionally small: a source snapshot, the compiler's
native cache, and a manifest tying the two together.  Building performs static
preparation and native compilation only; Python blocks are never executed.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

from . import __version__
from .compiler import ConflateError, Runner, _precompile_native_blocks, check_file, parse_program
from .languages import registrations


MANIFEST_NAME = "manifest.json"
MANIFEST_FORMAT = 1


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _inside(path: Path, directory: Path) -> bool:
    try:
        path.relative_to(directory)
    except ValueError:
        return False
    return True


def _safe_existing_output(path: Path) -> None:
    """Check that --force can replace a directory generated by Conflate.

    A non-empty arbitrary directory is not removed implicitly.  This keeps a
    typo in ``-o`` from recursively deleting user data.
    """
    if not path.exists():
        return
    if path.is_symlink():
        raise ConflateError(f"refusing to replace a symlink output: {path}")
    if not path.is_dir():
        raise ConflateError(f"output already exists and is not a directory: {path}")
    entries = list(path.iterdir())
    if not entries:
        return
    manifest = path / MANIFEST_NAME
    if not manifest.is_file():
        raise ConflateError(
            f"refusing to replace non-Conflate directory: {path} "
            "(remove it or choose another output)"
        )
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ConflateError(f"cannot inspect existing build directory {path}: {error}") from error
    if not isinstance(data, dict) or data.get("format") != MANIFEST_FORMAT:
        raise ConflateError(f"refusing to replace an unknown build directory: {path}")
    source_name = data.get("source")
    cache_name = data.get("build_root")
    if not isinstance(source_name, str) or not isinstance(cache_name, str):
        raise ConflateError(f"refusing to replace an incomplete build directory: {path}")
    if Path(source_name).name != source_name or source_name in {".", ".."}:
        raise ConflateError(f"refusing to replace a build with an unsafe source path: {path}")
    if Path(cache_name).as_posix() != ".conflate/build":
        raise ConflateError(f"refusing to replace a build with an unsafe cache path: {path}")
    expected = {MANIFEST_NAME, source_name, Path(cache_name).parts[0]}
    actual = {entry.name for entry in entries}
    if actual - expected:
        extras = ", ".join(sorted(actual - expected))
        raise ConflateError(f"refusing to remove unexpected files from build directory: {extras}")


def _remove_existing_output(path: Path) -> None:
    if not path.exists():
        return
    if path.is_symlink():
        raise ConflateError(f"refusing to replace a symlink output: {path}")
    if path.is_dir():
        # This is reached only after _safe_existing_output accepted the exact
        # target as empty or as a Conflate build directory.
        shutil.rmtree(path)
        return
    path.unlink()


_REGISTRATION_FIELDS = ("backend", "compiler", "runtime", "extension", "template", "compile", "run")


def _registration_snapshot(source_text: str, source: Path) -> dict[str, dict[str, Any]]:
    configured = registrations()
    names = {block.language for block in parse_program(source_text, str(source)) if block.language in configured}
    snapshot: dict[str, dict[str, Any]] = {}
    for name in sorted(names):
        entry = configured[name]
        snapshot[name] = {key: entry[key] for key in _REGISTRATION_FIELDS if key in entry}
    return snapshot


def _manifest_for(source: Path, build_root: Path, registrations_snapshot: dict[str, dict[str, Any]]) -> dict[str, Any]:
    return {
        "format": MANIFEST_FORMAT,
        "conflate_version": __version__,
        "platform": sys.platform,
        "architecture": platform.machine(),
        "source": source.name,
        "source_sha256": _sha256(source),
        "build_root": build_root.relative_to(source.parent).as_posix(),
        "registrations": registrations_snapshot,
    }


def build_source(source_path: Path, output_dir: Path, *, force: bool = False) -> Path:
    """Prepare a local build directory and return its path."""
    source_argument = Path(source_path)
    output_argument = Path(output_dir)
    if output_argument.is_symlink():
        raise ConflateError(f"refusing to use a symlink output: {output_argument}")
    source_path = source_argument.resolve()
    output_dir = output_argument.resolve()
    if not source_path.is_file():
        raise ConflateError(f"file not found: {source_path}")
    if output_dir == source_path:
        raise ConflateError("build output must be a directory, not the source file")
    if _inside(source_path, output_dir):
        raise ConflateError("source file cannot be inside the build output directory")
    if output_dir.exists() and not force:
        raise ConflateError(f"output already exists: {output_dir} (use --force to replace it)")
    if output_dir.exists():
        _safe_existing_output(output_dir)

    output_dir.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=f".{output_dir.name}-", dir=str(output_dir.parent)))
    try:
        snapshot = temporary / source_path.name
        shutil.copy2(source_path, snapshot)
        # check_file parses all blocks and validates Python syntax.  Native
        # helpers then compile artifacts into snapshot.parent/.conflate/build.
        check_file(snapshot)
        build_root = temporary / ".conflate" / "build"
        # Source paths are part of generated native source (for diagnostics)
        # and therefore of the compiler cache key.  Compile using the path the
        # snapshot will have after the atomic rename, while keeping artifacts
        # in the staging tree.
        logical_snapshot = output_dir / source_path.name
        source_text = snapshot.read_text(encoding="utf-8")
        _precompile_native_blocks(source_text, logical_snapshot, build_root=build_root)
        manifest = _manifest_for(snapshot, build_root, _registration_snapshot(source_text, snapshot))
        (temporary / MANIFEST_NAME).write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

        _remove_existing_output(output_dir)
        temporary.replace(output_dir)
    except (ConflateError, ValueError, OSError, TypeError, json.JSONDecodeError):
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    return output_dir


def _read_manifest(build_dir: Path) -> tuple[dict[str, Any], Path, Path]:
    build_dir = Path(build_dir).resolve()
    if not build_dir.is_dir():
        raise ConflateError(f"build directory not found: {build_dir}")
    manifest_path = build_dir / MANIFEST_NAME
    if not manifest_path.is_file():
        raise ConflateError(f"missing build manifest: {manifest_path}")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ConflateError(f"invalid build manifest: {error}") from error
    if not isinstance(manifest, dict):
        raise ConflateError("invalid build manifest: expected an object")
    if manifest.get("format") != MANIFEST_FORMAT:
        raise ConflateError("unsupported build manifest format")
    if manifest.get("conflate_version") != __version__:
        raise ConflateError(
            f"build was made by Conflate {manifest.get('conflate_version')!r}; "
            f"this runtime is {__version__}"
        )
    if manifest.get("platform") != sys.platform or manifest.get("architecture") != platform.machine():
        raise ConflateError("build host differs from this runtime; rebuild required")

    source_name = manifest.get("source")
    build_name = manifest.get("build_root")
    expected_hash = manifest.get("source_sha256")
    expected_registrations = manifest.get("registrations")
    if not isinstance(source_name, str) or not source_name:
        raise ConflateError("build manifest has no source snapshot")
    if not isinstance(build_name, str) or not build_name:
        raise ConflateError("build manifest has no native cache path")
    if not isinstance(expected_hash, str) or len(expected_hash) != 64:
        raise ConflateError("build manifest has an invalid source hash")
    if not isinstance(expected_registrations, dict):
        raise ConflateError("build manifest has no language registration snapshot")

    source = (build_dir / source_name).resolve()
    cache = (build_dir / build_name).resolve()
    if not _inside(source, build_dir) or not _inside(cache, build_dir):
        raise ConflateError("build manifest contains a path outside its directory")
    if not source.is_file():
        raise ConflateError(f"missing source snapshot: {source}")
    if _sha256(source) != expected_hash:
        raise ConflateError("source snapshot does not match the build manifest")
    try:
        current_registrations = _registration_snapshot(source.read_text(encoding="utf-8"), source)
    except (OSError, ValueError, ConflateError) as error:
        raise ConflateError(f"cannot inspect source language registrations: {error}") from error
    if current_registrations != expected_registrations:
        raise ConflateError("language registration changed; rebuild required")
    if not cache.is_dir():
        raise ConflateError(f"missing native cache: {cache}")
    return manifest, source, cache


def run_build(build_dir: Path) -> None:
    """Validate and execute a previously prepared local build."""
    _, source, cache = _read_manifest(Path(build_dir))
    Runner(source, build_root=cache).run()


def _which(command: str | None) -> str | None:
    if not command:
        return None
    return shutil.which(command) or (command if Path(command).is_file() else None)


def doctor_report() -> list[dict[str, Any]]:
    """Return availability diagnostics without invoking any toolchain."""
    configured = registrations()
    java_compiler = shutil.which("javac")
    java_runtime = shutil.which("java")
    entries: list[tuple[str, str, str | None]] = [
        ("python", "python", sys.executable),
        ("cpp", "cpp", os.environ.get("CXX") or shutil.which("g++") or shutil.which("clang++")),
        ("java", "java", java_compiler),
        ("go", "go", shutil.which("go")),
        ("rust", "rust", shutil.which("rustc")),
        ("javascript", "javascript", shutil.which("node")),
    ]
    report = [
        {"name": name, "backend": backend, "command": command, "available": bool(_which(command))}
        for name, backend, command in entries
    ]
    report[2]["runtime"] = java_runtime
    report[2]["available"] = bool(_which(java_compiler) and _which(java_runtime))
    for name, entry in sorted(configured.items()):
        backend = entry.get("backend", "external")
        command: str | None = entry.get("compiler") or entry.get("runtime")
        if backend == "external":
            run = entry.get("run")
            if isinstance(run, list) and run and isinstance(run[0], str):
                command = run[0]
        report.append(
            {"name": f"@{name}", "backend": backend, "command": command, "available": bool(_which(command))}
        )
    return report


def print_doctor() -> None:
    print(f"Conflate {__version__} toolchain diagnostics")
    for item in doctor_report():
        status = "ok" if item["available"] else "missing"
        command = item["command"] or "-"
        print(f"{item['name']}: {status} ({command})")
